# Versão inicial para aula 1
services:
  backend:
    build: ../filesfybackend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=filesfy_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  frontend:
    build: ../filesfyfrontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - backend

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: filesfy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: